import "bootstrap/dist/css/bootstrap.min.css";
import BootstrapClient from "./lib/bootstrapClient";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./ui/nav/navbar";
import { getServerSession } from "next-auth";
import SessionProvider from "./ui/auth/sessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Tsk4-mern app",
    description: "Generated by me",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <body className={inter.className}>
                <SessionProvider session={session}>
                {/* <SessionProvider
                    session={session}
                    refetchInterval={3}
                > */}
                    <NavBar></NavBar>
                    {children}
                </SessionProvider>
            </body>
            <BootstrapClient />
        </html>
    );
}
